### ISSUE TITLE
What is RUST cli

### ISSUE THREAD

**Issue by remotewhiteboard** [CommuteStream/tflgtfs#12]
And how can I get this to run on my mac? Thanks

**Comment by teburd** [comment]
Hi there, 

The readme is a bit unclear there, but its a program written in the rust language. You first need to install rust (very easy, check out https://rustup.rs).

The rest of the readme describes how to build and use the program, let me know if any of that is unclear

**Comment by remotewhiteboard** [comment]
Great thanks, got that installed. Now end up with this error:

--- stderr
src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
thread 'main' panicked at 'explicit panic', /Users/jjj/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.19/src/lib.rs:771
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I have made sure openssl is installed. I tried setting the env variable as you show int the readme, with no luck.

**Comment by teburd** [comment]
I actually don't have a Mac and do all my daily work/computer interactions with Linux, perhaps @arnau might be able to help more as he specifically wrote in that portion of the README to help build/use this on Mac.

There's some more hints on https://github.com/sfackler/rust-openssl that might help. Hopefully one of those things comes through for you.

**Comment by arnau** [comment]
Hi, I pulled the last `master` and did:

``` sh
cargo clean
OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include cargo build --release
```

Having:

OSX: 10.11.6
Rust: rustc 1.11.0 (9b21dcd6a 2016-08-15)

The safest command is the one rust-openssl suggests: 

```
OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include cargo build --release
```

Because it makes sure you use the right prefix.

All that said, make sure when you try again you first `cargo clean` to remove any leftover with a wrong linked lib.

**Comment by teburd** [comment]
Closing for now, please reopen if your still interested in this issue and the comments above haven't solved the problem
