### ISSUE TITLE
Temporal resolution

### ISSUE THREAD

**Issue by gac55** [CommuteStream/tflgtfs#14]
Many thanks for sharing this!

I'm trying to understand how fresh the data is that this accesses. Some TfL feeds are refreshed at 30second intervals, does this make use of these or longer resolution timed data. How often would you recommend running this?

Thanks

**Comment by teburd** [comment]
The data is fetched as a snapshot of the current API data and stored as a set of CSV files matching the GTFS spec. So at the time of the snapshot.

Let me know if that makes sense.

**Comment by gac55** [comment]
Thanks, it does!

I have noticed than running this fresh takes a considerable amount of time. However, when I run it subsequent times it re-uses something as it goes through the process in around in a minute. Does it recompute only if there are differences?

**Comment by teburd** [comment]
It caches most of the api results into a couple of files to avoid redownloading, fetching all the data from the TFL API is the longer part of the process but it still takes a good amount of time to transform the TFL API data into the GTFS format. The directory you run tflgtfs in should have a cache directory, that contains all the JSON downloaded from the TFL API and may be deleted if your concerned its reusing it.

**Comment by ludogithub** [comment]
Hi,

I'm trying to download the GTFS for TFL but I'm only getting service dates until October the 31st.

Thanks,

Ludovic

**Comment by teburd** [comment]
@ludogithub answering inline here, but please create another issue if this doesn't answer your question... this program does the work of downloading and transforming the TFL API into GTFS files, nothing more. If the service data from the TFL API contains only up to Oct 31st (most likely) then that is an issue with the TFL API rather than this program. Otherwise I would consider that a bug.

**Comment by teburd** [comment]
Closing this thread, since it seems dead, please reopen or create a new issue if you feel like thats wrong!

**Comment by ludogithub** [comment]
Thanks @bfrog for your answer, I was quite suprised an API would deliver out-of-date information. I'll try again today. Best, Ludo.
