### ISSUE TITLE
Error on running fetch-lines

### ISSUE THREAD

**Issue by double-u-a** [CommuteStream/tflgtfs#15]
Hello, I built on Ubuntu 16.04 with Rust 1.17.0, the build appeared successful and `cargo test --verbose` also seemed okay. However when I ran `target/release/tflgtfs fetch-lines` I recieved the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(invalid type: Map, 1, 1)', /checkout/src/libcore/result.rs:859
```
The backtrace is:
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: tflgtfs::cmd::load_lines
  11: tflgtfs::main
  12: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  15: __libc_start_main
  16: _start
```

And all that gets output is `cache/_line-route.txt` 
```
{"$type":"Tfl.Api.Presentation.Entities.ApiError, Tfl.Api.Presentation.Entities","timestampUtc":"2017-05-04T12:32:25.3380909Z","exceptionType":"EntityNotFoundException","httpStatusCode":404,"httpStatus":"NotFound","relativeUri":"/Line/Route","message":"The following line id is not recognised: Route"}
```

I've tried to have a look to see anything obvious but I'm not familiar with the Rust language and what the backtrace is exactly saying, hopefully this makes sense. Let me know if there is anything I can do to help.

But yes this CLI seems really perfect for analysing TfL data!

**Comment by idlem1nd** [comment]
Looks like an issue with an API that we rather hastily removed without proper deprecation - the /Line/Route API has been restored if you'd like to retry?

**Comment by double-u-a** [comment]
Great, I've rerun and it seems like its returning data now! 

I'm getting some occasional missing field errors now as I watch the printouts:
`Error decoding timetable: missing field "stations" at line 1 column 362`
`Error decoding timetable: missing field "lat" at line 1 column 15590`

These are happening a few times, although when it finishes I'll see if this actually affects anything significantly.

**Comment by double-u-a** [comment]
Okay the process completed with a lot of these sorts of errors as well:
```
Error (line virgin-trains-east-coast): The stop you selected has now been removed from the route, and therefore we cannot show you a timetable. The route page will be updated shortly to reflect these changes.

could not find shape for 15 490013766F to 490013573W!!!
```
I'm going to put it through a gtfs network building tool and report back to see how it looks!

**Comment by AnthonySu** [comment]
I encountered the same problem yesterday and still yet am not able to figure it out.

The message shows:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Ssl(OpenSslErrors([UnknownError { library: "SSL routines", function: "SSL23_GET_SERVER_HELLO", reason: "tlsv1 alert protocol version" }]))', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I am wondering how this could be fixed. I have both build few times and cargo clean before I build, still not working out.

**Comment by idlem1nd** [comment]
@AnthonySu judging by the reference to SSL protocol versions, this is probably due to older TLS versions not being supported https://blog.tfl.gov.uk/2016/12/21/developers-using-tfls-open-data-feeds/

I'm not sure how this is controlled in Rust, but it could be as simple as upgrading your client-side libraries?

**Comment by zshuLiu** [comment]
Hi
I installed the exporter successfully on Ubuntu 16.04 yesterday. However, I couldn't find an executable file. The command "./target/release/tflgtfs fetch-lines --format gtfs" could not been found when I used it. Do you have any ideas about it?

**Comment by teburd** [comment]
@zshuLiu did you build with rust first? cargo build --release ?

**Comment by zshuLiu** [comment]
@bfrog Yes I did. That problem has been solved becuz I made a stupid mistake. However I got a new problem. When I ran ./target/release/tflgtfs fetch-lines --format gtfs command, I received the following error
![52832804818284196](https://user-images.githubusercontent.com/37106584/37352182-954f58b0-26d4-11e8-8b48-02706bf8fc76.png)
