### ISSUE TITLE
trip_id values

### ISSUE THREAD

**Issue by arnau** [CommuteStream/tflgtfs#8]
Hi, I'm starting to look inside the GTFS files a bit more in detail.  I found the `trip_id` is quite long, e.g.: `264 490012696E to 490005855C16 scheduled Monday to Friday departs 00:00`.

What do you think about changing it to something more obscure but smaller? e.g. a UUID?

**Comment by teburd** [comment]
I'd say a hash would be a nicer way. One important aspect of the current format is that it's consistent over re-runs. So every time I run tflgtfs the trip_id should remain the same if nothing has changed. I do agree, the trip_id's are very long.

**Comment by arnau** [comment]
Ok, I did a first approach hashing the same composed tokens as MD5.  If we go down this road, do we want to hash more IDs?
